// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/dishes/dishes.proto

package dishes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DishRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DishRequest) Reset() {
	*x = DishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishRequest) ProtoMessage() {}

func (x *DishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishRequest.ProtoReflect.Descriptor instead.
func (*DishRequest) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{0}
}

func (x *DishRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DishesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes []*Dish `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *DishesResponse) Reset() {
	*x = DishesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishesResponse) ProtoMessage() {}

func (x *DishesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishesResponse.ProtoReflect.Descriptor instead.
func (*DishesResponse) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{1}
}

func (x *DishesResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type Dish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     *Type          `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Category *Category      `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	NutFact  *NutritionFact `protobuf:"bytes,5,opt,name=nut_fact,json=nutFact,proto3" json:"nut_fact,omitempty"`
	Tag      *Tag           `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	Recipe   string         `protobuf:"bytes,7,opt,name=recipe,proto3" json:"recipe,omitempty"`
}

func (x *Dish) Reset() {
	*x = Dish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{2}
}

func (x *Dish) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Dish) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Dish) GetNutFact() *NutritionFact {
	if x != nil {
		return x.NutFact
	}
	return nil
}

func (x *Dish) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *Dish) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeDish string `protobuf:"bytes,2,opt,name=type_dish,json=typeDish,proto3" json:"type_dish,omitempty"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{3}
}

func (x *Type) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Type) GetTypeDish() string {
	if x != nil {
		return x.TypeDish
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryDish string `protobuf:"bytes,2,opt,name=category_dish,json=categoryDish,proto3" json:"category_dish,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{4}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetCategoryDish() string {
	if x != nil {
		return x.CategoryDish
	}
	return ""
}

type NutritionFact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Calories      float32 `protobuf:"fixed32,2,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins      float32 `protobuf:"fixed32,3,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats          float32 `protobuf:"fixed32,4,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbohydrates float32 `protobuf:"fixed32,5,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
}

func (x *NutritionFact) Reset() {
	*x = NutritionFact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NutritionFact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NutritionFact) ProtoMessage() {}

func (x *NutritionFact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NutritionFact.ProtoReflect.Descriptor instead.
func (*NutritionFact) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{5}
}

func (x *NutritionFact) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NutritionFact) GetCalories() float32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *NutritionFact) GetProteins() float32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *NutritionFact) GetFats() float32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *NutritionFact) GetCarbohydrates() float32 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagDish string `protobuf:"bytes,2,opt,name=tag_dish,json=tagDish,proto3" json:"tag_dish,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dishes_dishes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dishes_dishes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_dishes_dishes_proto_rawDescGZIP(), []int{6}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetTagDish() string {
	if x != nil {
		return x.TagDish
	}
	return ""
}

var File_proto_dishes_dishes_proto protoreflect.FileDescriptor

var file_proto_dishes_dishes_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2f, 0x64,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x36, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x44, 0x69,
	0x73, 0x68, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22, 0xe3, 0x01, 0x0a, 0x04, 0x44,
	0x69, 0x73, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69,
	0x73, 0x68, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x08, 0x6e, 0x75, 0x74, 0x5f, 0x66,
	0x61, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x2e, 0x4e, 0x75, 0x74, 0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x63, 0x74,
	0x52, 0x07, 0x6e, 0x75, 0x74, 0x46, 0x61, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2e,
	0x54, 0x61, 0x67, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65,
	0x22, 0x33, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x64, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x44, 0x69, 0x73, 0x68, 0x22, 0x3f, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x64, 0x69,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x44, 0x69, 0x73, 0x68, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x4e, 0x75, 0x74, 0x72, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x66, 0x61, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79, 0x64,
	0x72, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x63, 0x61, 0x72,
	0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x03, 0x54, 0x61,
	0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x64, 0x69, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x44, 0x69, 0x73, 0x68, 0x32, 0x47, 0x0a, 0x0b,
	0x44, 0x69, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dishes_dishes_proto_rawDescOnce sync.Once
	file_proto_dishes_dishes_proto_rawDescData = file_proto_dishes_dishes_proto_rawDesc
)

func file_proto_dishes_dishes_proto_rawDescGZIP() []byte {
	file_proto_dishes_dishes_proto_rawDescOnce.Do(func() {
		file_proto_dishes_dishes_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dishes_dishes_proto_rawDescData)
	})
	return file_proto_dishes_dishes_proto_rawDescData
}

var file_proto_dishes_dishes_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dishes_dishes_proto_goTypes = []interface{}{
	(*DishRequest)(nil),    // 0: dishes.DishRequest
	(*DishesResponse)(nil), // 1: dishes.DishesResponse
	(*Dish)(nil),           // 2: dishes.Dish
	(*Type)(nil),           // 3: dishes.Type
	(*Category)(nil),       // 4: dishes.Category
	(*NutritionFact)(nil),  // 5: dishes.NutritionFact
	(*Tag)(nil),            // 6: dishes.Tag
}
var file_proto_dishes_dishes_proto_depIdxs = []int32{
	2, // 0: dishes.DishesResponse.dishes:type_name -> dishes.Dish
	3, // 1: dishes.Dish.type:type_name -> dishes.Type
	4, // 2: dishes.Dish.category:type_name -> dishes.Category
	5, // 3: dishes.Dish.nut_fact:type_name -> dishes.NutritionFact
	6, // 4: dishes.Dish.tag:type_name -> dishes.Tag
	0, // 5: dishes.DishService.GetDishes:input_type -> dishes.DishRequest
	1, // 6: dishes.DishService.GetDishes:output_type -> dishes.DishesResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_dishes_dishes_proto_init() }
func file_proto_dishes_dishes_proto_init() {
	if File_proto_dishes_dishes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dishes_dishes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dishes_dishes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DishesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dishes_dishes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dishes_dishes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dishes_dishes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dishes_dishes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NutritionFact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dishes_dishes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dishes_dishes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dishes_dishes_proto_goTypes,
		DependencyIndexes: file_proto_dishes_dishes_proto_depIdxs,
		MessageInfos:      file_proto_dishes_dishes_proto_msgTypes,
	}.Build()
	File_proto_dishes_dishes_proto = out.File
	file_proto_dishes_dishes_proto_rawDesc = nil
	file_proto_dishes_dishes_proto_goTypes = nil
	file_proto_dishes_dishes_proto_depIdxs = nil
}
